[versions]
collar = "1.4.0"
gradle = "8.13.2"
lint = "31.13.2"
kotlin = "2.1.20"
coroutines = "1.8.1"
serialization = "1.8.1"
poet = "2.2.0"
inject = "0.8.0"
core = "1.15.0"
appcompat = "1.7.1"
activity = "1.9.3"
fragment = "1.8.5"
lifecycle = "2.8.7"
recyclerview = "1.4.0"
room = "2.8.4"
startup = "1.2.0"
dynamicanimation = "1.1.0"
design = "1.12.0"
detekt = "1.23.8"
ktlintplugin = "14.0.1"
ktlint = "1.8.0"
dokka = "2.1.0"
junit = "4.13.2"
extjunit = "1.3.0"
coretesting = "2.2.0"
testcorektx = "1.7.0"
mockito = "4.11.0"
espresso = "3.7.0"

[libraries]
libraryannotations = { module = "com.infinum.collar:collar-annotations", version.ref = "collar" }
librarycore = { module = "com.infinum.collar:collar-core", version.ref = "collar" }
libraryprocessor = { module = "com.infinum.collar:collar-processor", version.ref = "collar" }
librarygradle = { module = "com.infinum.collar:collar-plugin", version.ref = "collar" }
librarygenerator = { module = "com.infinum.collar:collar-generator", version.ref = "collar" }
libraryui = { module = "com.infinum.collar:collar-ui", version.ref = "collar" }
libraryuinoop = { module = "com.infinum.collar:collar-ui-no-op", version.ref = "collar" }

tools-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
tools-lintapi = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
tools-lintchecks = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
tools-linttests = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

serialization-gradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

metadata = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

material = { module = "com.google.android.material:material", version.ref = "design" }

poet = { module = "com.squareup:kotlinpoet", version.ref = "poet" }

inject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "inject" }
inject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "inject" }

detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintplugin" }

dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

junit = { module = "junit:junit", version.ref = "junit" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coretesting" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "extjunit" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "testcorektx" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }

[bundles]
androidx = [
    "androidx-core",
    "androidx-appcompat",
    "androidx-activity",
    "androidx-fragment",
    "androidx-lifecycle-viewmodel",
    "androidx-lifecycle-livedata",
    "androidx-lifecycle-runtime",
    "androidx-recyclerview",
    "androidx-dynamicanimation",
    "androidx-startup",
    "androidx-room-runtime",
    "androidx-room-ktx"
]