[versions]
collar = "1.4.0"
gradle = "8.8.2"
lint = "30.3.1"
kotlin = "2.1.20"
coroutines = "1.6.4"
serialization = "1.5.0"
poet = "1.12.0"
inject = "0.6.1"
core = "1.9.0"
appcompat = "1.6.1"
activity = "1.8.0"
fragment = "1.5.5"
lifecycle = "2.6.0"
recyclerview = "1.3.0"
room = "2.5.0"
startup = "1.1.1"
dynamicanimation = "1.0.0"
design = "1.8.0"
detekt = "1.23.8"
ktlintplugin = "10.3.0"
ktlint = "0.45.2"
cpd = "3.3"
dokka = "1.8.10"

[libraries]
libraryannotations = { module = "com.infinum.collar:collar-annotations", version.ref = "collar" }
librarycore = { module = "com.infinum.collar:collar-core", version.ref = "collar" }
libraryprocessor = { module = "com.infinum.collar:collar-processor", version.ref = "collar" }
librarygradle = { module = "com.infinum.collar:collar-plugin", version.ref = "collar" }
librarygenerator = { module = "com.infinum.collar:collar-generator", version.ref = "collar" }
libraryui = { module = "com.infinum.collar:collar-ui", version.ref = "collar" }
libraryuinoop = { module = "com.infinum.collar:collar-ui-no-op", version.ref = "collar" }

tools-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
tools-lintapi = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
tools-lintchecks = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
tools-linttests = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

serialization-gradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

metadata = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

material = { module = "com.google.android.material:material", version.ref = "design" }

poet = { module = "com.squareup:kotlinpoet", version.ref = "poet" }

inject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "inject" }
inject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "inject" }

detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintplugin" }

cpd = { module = "de.aaschmid:gradle-cpd-plugin", version.ref = "cpd" }

dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

[bundles]
androidx = [
    "androidx-core",
    "androidx-appcompat",
    "androidx-activity",
    "androidx-fragment",
    "androidx-lifecycle-viewmodel",
    "androidx-lifecycle-livedata",
    "androidx-lifecycle-runtime",
    "androidx-recyclerview",
    "androidx-dynamicanimation",
    "androidx-startup",
    "androidx-room-runtime",
    "androidx-room-ktx"
]